### ISSUE TITLE
undefined method `per_page' for Array

### ISSUE THREAD

**Issue by EllinaKuznetcova** [davydovanton/hanami-pagination#3]
Hello,

I added gem and followed usage tips, but when I call 
```
repo = BookRepository.new
@books = all_for_page(repo.all)
```
I get error `undefined method per_page for Array`

I use hanami-model v.1.0.0.

**Comment by davydovanton** [comment]
Hey, you need to put relation to `all_for_page`  method. In your case, it's mean that you need to call it like this: `all_for_page(repo.books)`

**Comment by davydovanton** [comment]
Sorry, I found this code in documentation. It's wrong and I'll fix it. Thanks!

**Comment by EllinaKuznetcova** [comment]
Thank you!
